name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Run Python script in WSL
        shell: powershell
        run: |
          wsl.exe -- bash -lc 'chmod +x /home/ubuntu/src/SDS2Prod-sds2/install_src/echo.sh && /home/ubuntu/src/SDS2Prod-sds2/install_src/build_release.py'
 
